### PR TITLE
fix:about us page fixes

### LINKED ISSUE #177: About us Page fixes
- [x]  "Departamentos" -> "Pelouros"
- [x] Subtitle “Conhece os departamentos que compõem a tua AEFEUP e quais as suas áreas de atuação!”
- [x]  Descrease space between lines, ex: ”Margarida Pelicano”
- [x] When changing depatarments, images stick to the old ones and then update, are the keys being the same?
- [x] Change avatar background color to red? (optional)

### PR DESCRIPTION
**Pull request by rubuy-74**
Closes #177

### CODE REVIEW

File: app/(site)/(aefeup)/about/MenuDescription.tsx [hunk 1]
```diff
@@ -27,8 +27,7 @@ const MenuDescription = ({ sections }: Props) => {
   return (sections.length > 0 &&
     <div className="mx-auto max-w-7xl">
       <SectionHeader
-        title="Departamentos"
-        subtitle="Departamentos"
+        title="Pelouros"
```
Comment (thePeras) [inline app/(site)/(aefeup)/about/MenuDescription.tsx:30]: don't forget the subtitle

Comment (rubuy-74) [reply app/(site)/(aefeup)/about/MenuDescription.tsx:30]: Isn't it just repetetive? to have the same thing twice one below the other?

Comment (thePeras) [reply app/(site)/(aefeup)/about/MenuDescription.tsx:30]: The new one, as described in the issue

Comment (rubuy-74) [reply app/(site)/(aefeup)/about/MenuDescription.tsx:30]: yeah, I didn't see it :smiley:

**Review by thePeras — APPROVED** [review]
