### PR TITLE
fix:association page

### LINKED ISSUE #178: Associations Page fixes
- [ ] Max of 6 associations per line
- [ ] Each assocation should have the same width
- [ ] Associations Description not showing

### PR DESCRIPTION
**Pull request by rubuy-74**
Closes #178

### CODE REVIEW

File: app/(site)/(aefeup)/associations/client.tsx [hunk 1]
```diff
@@ -46,43 +24,41 @@ const AssociationsClientPage = ({ associations }) => {
...
+                            Núcleos da AEFEUP
+                        </h1>
+                        <div className="flex justify-center items-center mt-10">
+                            <div className="mx-auto grid grid-cols-1 md:grid-cols-3 lg:grid-cols-6 gap-5">
+                                {aefeup_associations.map((association, index) => {
+                                    return (
+                                        <AssociationCard association={association} key={index} />
+                                    );
+                                })}
+                            </div>
```
Comment (thePeras) [inline app/(site)/(aefeup)/associations/client.tsx]: grid makes it not cool when there is just on, for example, it will not center.
Can you change it to flex and flex-wrap? Forget about the absolute number of 6 :/

Comment (rubuy-74) [reply app/(site)/(aefeup)/associations/client.tsx]: done :)

**Review by thePeras — APPROVED** [review]
